In [1]:
!pip install mxnet

  Found existing installation: numpy 1.17.0
    Uninstalling numpy-1.17.0:
      Successfully uninstalled numpy-1.17.0
  Found existing installation: requests 2.22.0
    Uninstalling requests-2.22.0:
      Successfully uninstalled requests-2.22.0


tensorboard 2.0.2 has requirement requests<3,>=2.21.0, but you'll have requests 2.18.4 which is incompatible.
tensorboard 2.0.2 has requirement setuptools>=41.0.0, but you'll have setuptools 39.1.0 which is incompatible.
google-auth 1.7.1 has requirement setuptools>=40.3.0, but you'll have setuptools 39.1.0 which is incompatible.
You are using pip version 10.0.1, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [2]:
import mxnet

C:\Users\ALLU\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [6]:
import mxnet as mx
from mxnet import nd
mx.random.seed(1)

In [11]:
nd.empty((3,4))


[[0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 1.429324e-42 0.000000e+00]
 [0.000000e+00 8.448937e-39 0.000000e+00 1.373272e-43]]
<NDArray 3x4 @cpu(0)>

In [12]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [ ]:
#matrix with zero mean and unit varience 

In [14]:
x=nd.random_normal(0,1,shape=(3,4))
x


[[ 0.1266448  -0.17841923  0.7647921  -0.21776067]
 [ 2.2257879  -0.6883264   0.84155583 -0.61584127]
 [ 0.01961146 -0.24421656 -0.13420728 -0.5180439 ]]
<NDArray 3x4 @cpu(0)>

In [15]:
nd.exp(x)


[[1.1350138  0.8365916  2.1485476  0.8043179 ]
 [9.2607765  0.5024162  2.3199737  0.5401863 ]
 [1.0198051  0.783318   0.8744088  0.59568465]]
<NDArray 3x4 @cpu(0)>

In [18]:
#multiplication with transpose

In [17]:
nd.dot(x,x.T)


[[0.68019897 1.1824164  0.05622553]
 [1.1824164  6.5154014  0.41784155]
 [0.05622553 0.41784155 0.34640738]]
<NDArray 3x3 @cpu(0)>

In [19]:
print('id(x):',id(x))

id(x): 13818340688


In [21]:
nd.arange(3)


[0. 1. 2.]
<NDArray 3 @cpu(0)>

In [24]:
x


[[ 0.1266448  -0.17841923  0.7647921  -0.21776067]
 [ 2.2257879  -0.6883264   0.84155583 -0.61584127]
 [ 0.01961146 -0.24421656 -0.13420728 -0.5180439 ]]
<NDArray 3x4 @cpu(0)>

In [23]:
x.reshape((3,2))


[[ 0.1266448  -0.17841923]
 [ 0.7647921  -0.21776067]
 [ 2.2257879  -0.6883264 ]]
<NDArray 3x2 @cpu(0)>

In [25]:
x.asnumpy()

array([[ 0.1266448 , -0.17841923,  0.7647921 , -0.21776067],
       [ 2.2257879 , -0.6883264 ,  0.84155583, -0.61584127],
       [ 0.01961146, -0.24421656, -0.13420728, -0.5180439 ]],
      dtype=float32)

In [26]:
nd.array(x)


[[ 0.1266448  -0.17841923  0.7647921  -0.21776067]
 [ 2.2257879  -0.6883264   0.84155583 -0.61584127]
 [ 0.01961146 -0.24421656 -0.13420728 -0.5180439 ]]
<NDArray 3x4 @cpu(0)>

In [27]:
nd.array([3.0])


[3.]
<NDArray 1 @cpu(0)>

In [ ]:
#tensors

In [38]:
f=nd.arange(72).reshape(3,3,4)

In [41]:
g=f*2

In [44]:
a=nd.ones(shape=(3,4))

In [45]:
b=nd.ones(shape=(4,5))

In [46]:
nd.dot(a,b)


[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
<NDArray 3x5 @cpu(0)>

In [47]:
a


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

In [48]:
b


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<NDArray 4x5 @cpu(0)>

In [52]:
#l1norm

In [55]:
x


[[ 0.1266448  -0.17841923  0.7647921  -0.21776067]
 [ 2.2257879  -0.6883264   0.84155583 -0.61584127]
 [ 0.01961146 -0.24421656 -0.13420728 -0.5180439 ]]
<NDArray 3x4 @cpu(0)>

In [57]:
nd.sum(x)


[1.3815767]
<NDArray 1 @cpu(0)>

In [56]:
nd.sum(nd.abs(x))


[6.575207]
<NDArray 1 @cpu(0)>

In [ ]:
#differentiation 

In [114]:
g=nd.array([[1,2],[3,4]])

In [96]:
#g=2*(h**2)

In [97]:
from mxnet import nd,autograd

In [106]:
g.attach_grad()

In [107]:
with autograd.record():
    y=g*2
    z=y*g
    

In [108]:
z.backward()

In [109]:
g.grad


[[ 4.  8.]
 [12. 16.]]
<NDArray 2x2 @cpu(0)>

In [117]:
g=nd.array([[1,2],[3,4]])

In [120]:
with autograd.record():
    y=g*2
    z=y*g
    


In [121]:
head_grad=nd.array([[10,1],[.1,0.1]])

    

In [124]:
g.attach_grad()

In [130]:
from mxnet import nd,autograd,gluon

In [136]:
nd.arange(-5,5,0.1)


[-5.         -4.9        -4.8        -4.7        -4.6        -4.5
 -4.4        -4.3        -4.2        -4.1        -4.         -3.9
 -3.8        -3.6999998  -3.6        -3.5        -3.4        -3.3
 -3.1999998  -3.1        -3.         -2.8999999  -2.8        -2.7
 -2.6        -2.5        -2.3999999  -2.3        -2.2        -2.1
 -2.         -1.8999999  -1.8        -1.7        -1.5999999  -1.5
 -1.3999999  -1.3        -1.2        -1.0999999  -1.         -0.9000001
 -0.7999997  -0.6999998  -0.5999999  -0.5        -0.4000001  -0.2999997
 -0.19999981 -0.0999999   0.          0.0999999   0.20000029  0.3000002
  0.4000001   0.5         0.5999999   0.7000003   0.8000002   0.9000001
  1.          1.0999999   1.2000003   1.3000002   1.4000001   1.5
  1.5999999   1.7000003   1.8000002   1.9000001   2.          2.1
  2.2000003   2.3000002   2.4         2.5         2.6         2.7000003
  2.8000002   2.9         3.          3.1000004   3.1999998   3.3000002
  3.4000006   3.5         3.6000004   3